Practice 4
tamarinvs19/ScalaSpbsu21 pull request #4
Opened 2021-03-04 19:20 UTC by tamarinvs19

2021-03-08 11:13 UTC, fuCtor requested changes

2021-03-08 11:13 UTC, fuCtor commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  implicit final def IntMonoid: Monoid[Int] =
в данном случае лучше использовать val

2021-03-08 11:13 UTC, fuCtor commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  implicit def IntCompAbs: Comparator[Int] =
два одинаковых имплисита по типу, нужно оставить только один

2021-03-08 11:31 UTC, tamarinvs19 commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  implicit def IntCompAbs: Comparator[Int] =
А если я хочу использовать разные компараторы для Int, например, как правильно сделать? 
В тестах я просто внутри функции импортировал нужный, поэтому конфликтов не было

2021-03-08 11:33 UTC, tamarinvs19 commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  implicit final def IntMonoid: Monoid[Int] =
Поменял

2021-03-10 17:41 UTC, fuCtor commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  implicit def IntCompAbs: Comparator[Int] =
Лучше разнести по разным объектам,  чтобы  если сделают  import Monoid._ не было коллизии.

2021-03-10 17:41 UTC, fuCtor approved these changes

2021-03-10 17:47 UTC, merged